version: "3"
services:
  front-end:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  backend:
    build:
      context: ./test-server
      dockerfile: Dockerfile
    ports:
      - "8082:3000"
      - "3000:3000"
